schedular/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('timetable.urls'))
]

timetable/urls.py
from django.urls import path
from . import views
app_name = 'timetable'
urlpatterns = [
    path('', views.index, name='index'),
    path('edit/<int:id>', views.edit, name='edit'),
    path('register', views.register, name='register')
]

timetable/models.py
from django.db import models
from django.conf import settings
from django.core.validators import MinValueValidator, MaxValueValidator

# Create your models here.
class DayChoice(models.IntegerChoices):
    MONDAY = 0
    TUESDAY = 1
    WEDNESDAY = 2
    THURSDAY = 3
    FRIDAY = 4
    SATURDAY = 5
    SUNDAY = 6

class TimeTable(models.Model):
    name = models.CharField(max_length=30)
    duration_of_each_lec = models.IntegerField()
    day_off = models.IntegerField(choices = DayChoice.choices, null=True, blank=True)
    starts_at = models.TimeField(auto_now=False, auto_now_add=False)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='all_timetable')
    no_of_lec = models.IntegerField(validators=[MinValueValidator(2), MaxValueValidator(14)])
    def __str__(self):
        return self.name

class Subject(models.Model):
    name_of_sub = models.CharField(max_length=30)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='all_sub')
    def __str__(self):
        return f'{self.name_of_sub}'    

class SubjectCell(models.Model):
    day = models.IntegerField(choices = DayChoice.choices)
    of_time_table = models.ForeignKey(TimeTable, on_delete=models.CASCADE, related_name='sub_cell')
    period = models.IntegerField(validators=[MaxValueValidator(14)])
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE, related_name="cell")

    

timetable/forms.py
from django import forms
from .models import TimeTable, Subject, SubjectCell
from django.utils.translation import gettext_lazy as _
from django.contrib.admin import widgets 

class TimeTableForm(forms.ModelForm):
    class Meta:
        model = TimeTable
        fields = ['name', 'duration_of_each_lec', 'day_off', 'starts_at', 'no_of_lec']
        labels = {
            'day_off': _('Holiday on')
        }
        labels = {
            'starts_at': 'Starting Time of First Lecture (hh:mm) eg.05:00 '
        }
class SubjectForm(forms.ModelForm):
    class Meta:
        model = Subject
        fields = ['name_of_sub']
        labels = {
            'name_of_sub': 'Name of Subject'
        }
class SubjectCellForm(forms.ModelForm):
    class Meta:
        model = SubjectCell
        fields = ['subject', 'day', 'period']
        

timetable/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponseRedirect
from datetime import datetime, timedelta, date
from .models import DayChoice, TimeTable, Subject
from .forms import TimeTableForm, SubjectForm, SubjectCellForm
from django.views.generic import ListView
from django.contrib.auth.models import User
from django.contrib.auth import login
from django.db import IntegrityError
# Create your views here.
def index(request):
    form = TimeTableForm()
    ctx = {'form': form}
    if request.user.is_authenticated:
        ctx["all_timetable"] = TimeTable.objects.filter(user=request.user)
    if request.method == 'POST':
        form = TimeTableForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.user = request.user
            obj.save()
            return HttpResponseRedirect(reverse('timetable:edit', args=(obj.id,)))
        else:
            ctx["form"]=form
            ctx["error"]=True
            return render(request, 'timetable/index.html', ctx)
    
    return render(request, 'timetable/index.html',ctx)

def edit(request, id):
    # get the timetable which is to be edited from data base
    this_timetable = request.user.all_timetable.filter(id=id)[0]

    # getting time head which the timing of lecture start and end
    time_head = list()
    starts_at = this_timetable.starts_at
    for _ in range(this_timetable.no_of_lec):
        n_dtime = datetime.combine(date.today(), starts_at) + timedelta(minutes=this_timetable.duration_of_each_lec)
        time_head.append(f'{starts_at} - {n_dtime.time()}')
        starts_at = n_dtime.time()
    
    # creating a two dimension list with subject name if there is a lecture added else None 
    list_tt = [[None for _ in range(this_timetable.no_of_lec)] for _ in range(7)]
    for cell in this_timetable.sub_cell.all():
        list_tt[cell.day][cell.period] = cell.subject.name_of_sub
    
    # get all days in the choices available
    all_days = [DayChoice(j).label for j in range(7)]
    mylist = zip(list_tt, all_days)
    ctx = {'id': id, 'mylist': mylist, 'time_head': time_head}
    subform = SubjectForm()
    ctx['subform'] = subform
    cellform = SubjectCellForm()
    # get all the subjects available
    all_subjects = Subject.objects.filter(user = request.user.id)
    ctx['all_subjects'] = all_subjects
    ctx['cellform'] = cellform
    ctx['title'] = this_timetable.name
    if request.method == "POST":
        if "subjec" in request.POST:
            subform = SubjectForm(request.POST)
            if subform.is_valid():
                obj = subform.save(commit=False)
                obj.user = request.user
                obj.save()
                return HttpResponseRedirect(reverse('timetable:edit', args=(id,)))
        elif "cell" in request.POST:
            cellform = SubjectCellForm(request.POST)
            if cellform.is_valid():
                obj = cellform.save(commit=False)
                inst = TimeTable.objects.get(id=id)
                period = cellform.cleaned_data.get('period')
                obj.of_time_table = inst
                obj.period = period - 1
                obj.save()
                return HttpResponseRedirect(reverse('timetable:edit', args=(id,)))
    return render(request, 'timetable/edit.html', ctx)

def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]
        first = request.POST["first"]
        last = request.POST["last"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "timetable/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password, first_name=first, last_name=last)
            user.save()
        except IntegrityError:
            return render(request, "timetable/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("timetable:index"))
    else:
        return render(request, "timetable/register.html")

timetable/templates/timetable/edit.html
{% extends 'timetable/base.html' %}
{% load crispy_forms_tags %}
{% block body %}
    <div class="container">    
        <form action="{% url 'timetable:edit' id %}" method="POST">
            {% csrf_token %}
            {{ cellform|crispy }}
            <input class="btn btn-primary" type="submit" name="cell" value="Add/Update to TimeTable">
        </form>
        <h1 class="text-center">{{ title }}</h1>
        <table border="2" cellspacing="3" align="center">
        <tr>
        <td align="center">
        {% for time in time_head %}
        <td>{{ time }}
        {% endfor %}
        </tr>
        {% for day, day_name in mylist %}
            <tr>
            <td align="center">{{ day_name }}
            {% for lec in day %}
            <td align="center">{% if lec is none %}---{% else %}{{ lec }}{% endif %}<br>
            {% endfor %}
            </tr>
        {% endfor %}
        </table>
        <form action="{% url 'timetable:edit' id %}" method="POST">
            {% csrf_token %}
            {{ subform|crispy }}
            <input class='btn btn-primary' type="submit" name="subjec" value="Add Subject">
        </form>
    </div>
{% endblock body %}

timetable/templates/timetable/index.html
{% extends 'timetable/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block body %}
    <div class='top-hd'>
    <img id="bg-img" src="{% static 'timetable/images/head-img.webp' %}">
    <button class="create-table-lg myBtn" id="hrBtn">Create TimeTable</button>
    <div>
    {% if user.is_authenticated %}
        <div class="container">
            <h1 class="p-2">Your TimeTables</h1>
            <ul>
            {% for timetable in all_timetable %}
            <li><a href="{% url 'timetable:edit' timetable.id %}">{{ timetable }}</a></li>
            {% endfor %}
            </ul>
        </div>
    {% endif %}
    <div id="myModal" class="modal">

        <!-- Modal content -->
        <div class="modal-content">
            <span class="close">&times;</span>
            {% if user.is_authenticated %}
                <form class='m-auto' style='width: 70%' method='POST' action="{% url 'timetable:index' %}">
                {% csrf_token %}
                {{ form|crispy }}
                <input type='submit' class='btn btn-primary' value='Create TimeTable'>
                </form>
            {% else %}
                <h1>Please Login</h1>
            {% endif %}
        </div>

    </div>
    
    {% if error %}
    <script>
    var modal = document.getElementById("myModal");
    modal.style.display = "block";
    </script>
    {% endif %}
    
{% endblock body %}

timetable/templates/timetable/register.html
{% extends "timetable/base.html" %}

{% block navbar %}
{% endblock navbar %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'timetable:register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        
        <div class="form-group">
            <input class="form-control" type="text" name="first" placeholder="First Name">
        </div>
        
        <div class="form-group">
            <input class="form-control" type="text" name="last" placeholder="Last Name">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'login' %}">Log In here.</a>

{% endblock %}

timetable/templates/timetable/temp.html
{% comment %} {{ timet.subject_set.get.name_of_sub }} {% endcomment %}
{% for cell in timet %}
    {{ cell.subject_set.get }}<br>
    {{ cell.period }}<br>
    {{ cell.day }}<br>
{% endfor %}
{% comment %} {{ c }} {% endcomment %}
{{ e }}
{% comment %} {{ i }} {% endcomment %}
{{ mylist }}
<table border="2" cellspacing="3" align="center">
<tr>
 <td align="center">
 {% for time in e %}
 <td>{{ time }}
 {% endfor %}
</tr>
{% for day, day_name in mylist %}
    <tr>
    <td align="center">{{ day_name }}
    {% for lec in day %}
    <td align="center">{% if lec is none %}---{% else %}{{ lec }}{% endif %}<br>
    {% endfor %}
    </tr>
{% endfor %}
{% comment %} <tr>
 <td align="center">TUESDAY
 <td align="center"><font color="blue">SUB1<br>
 <td align="center"><font color="red">SUB2<br>
 <td align="center"><font color="pink">SUB3<br>
 <td align="center">---
 <td align="center"><font color="orange">SUB4<BR>
 <td align="center"><font color="maroon">SUB5<br>
 <td align="center">library
</tr>
<tr>
 <td align="center">WEDNESDAY
 <td align="center"><font color="pink">SUB1<br>
 <td align="center"><font color="orange">SUB2<BR>
 <td align="center"><font color="brown">SWA<br>
 <td align="center">---
 <td colspan="3" align="center"><font color="green"> lab
</tr>
<tr>
 <td align="center">THURSDAY
 <td align="center">SUB1<br>
 <td align="center"><font color="brown">SUB2<br>
 <td align="center"><font color="orange">SUB3<BR>
 <td align="center">---
 <td align="center"><font color="blue">SUB4<br>
 <td align="center"><font color="red">SUB5<br>
 <td align="center">library
</tr>
<tr>
 <td align="center">FRIDAY
 <td align="center"><font color="orange">SUB1<BR>
 <td align="center"><font color="maroon">SUB2<br>
 <td align="center"><font color="blue">SUB3<br>
 <td align="center">---
 <td align="center"><font color="pink">SUB4<br>
 <td align="center"><font color="brown">SUB5<br>
 <td align="center">library
</tr>
<tr>
 <td align="center">SATURDAY
 <td align="center"><font color="red">SUB1<br>
 <td colspan="3" align="center">seminar
 <td align="center"><font color="pink">SUB4<br>
 <td align="center"><font color="brown">SUB5<br>
 <td align="center">library
</tr> {% endcomment %}
{% comment %} <html>
<head>
   <title>time table</title>
</head>
<body bgcolor="skyblue">
<H1><FONT COLOR="DARKCYAN"><CENTER>COLLEGE TIME TABLE</FONT></H1>

</body>
</html> {% endcomment %}